### ISSUE TITLE
Tiny bug return...

### ISSUE THREAD

**Issue by TotoR115** [Gibberlings3/BG1NPC#100]
@Gitjas 
There are 3 instances of `ADD_MEMORIZED_SPELL ~spwi401~` in nythrun_fixes.tpa. 

two are correct: 
https://github.com/Gibberlings3/BG1NPC/blob/d4ab04576106f368847964e89f40ff494fd74f2a/bg1npc/core/tpa/nythrun_fixes.tpa#L791
https://github.com/Gibberlings3/BG1NPC/blob/d4ab04576106f368847964e89f40ff494fd74f2a/bg1npc/core/tpa/nythrun_fixes.tpa#L299

and one is not: https://github.com/Gibberlings3/BG1NPC/blob/d4ab04576106f368847964e89f40ff494fd74f2a/bg1npc/core/tpa/nythrun_fixes.tpa#L358

_Originally posted by @TotoR115 in https://github.com/Gibberlings3/BG1NPC/issues/90#issuecomment-1158097507_

**Comment by Gitjas** [comment]
Thanks, fixed for v29.
