### ISSUE TITLE
Some names in bg1npc_tiaxqst.tpa should be moved into bg1npc_tmp.tra

### ISSUE THREAD

**Issue by abalabokhin** [Gibberlings3/BG1NPC#110]
There are six names in the file https://github.com/Gibberlings3/BG1NPC/blob/master/bg1npc/phase2/tpa/bg1npc_tiaxqst.tpa:
Belgin, Karris, Alvo, Leti, Zed, Mati. They cannot be translated as for now.
Is it possible to move them into https://github.com/Gibberlings3/BG1NPC/blob/master/bg1npc/tra/english/bg1npc_tmp.tra (and for other languages as well) and have the references to them in bg1npc_tiaxqst.tpa?

**Comment by Gitjas** [comment]
Sounds like a good idea.

**Comment by abalabokhin** [comment]
I already fixed it in my branch (we are revising Russian translation there, cause it is far from ideal): https://github.com/abalabokhin/bg1npc. It should be ready in couple of month (hopefully soner). Thus, pull request from me will include these names moving. Or you can do it by yourself and I will merge this change into my branch.

**Comment by abalabokhin** [comment]
Close, since pull request with these changes is accepted.

**Comment by abalabokhin** [comment]
Close
