### ISSUE TITLE
WARNING: REPLACE_CRE_ITEM: Unknown flag UNDROPPABLE&UNSTEALABLE. Defaulting to NONE for flags.

### ISSUE THREAD

**Issue by agb1** [Gibberlings3/BG1NPC#22]
Using WeiDU v240.

Installing [The BG1 NPC Project: Female Romance Challenges, Ajantis vs Xan vs Coran] [v22.4]

BG:EE install detected.
Copying and patching 1 file ...
loading 1 tra file
loading 1 tra file
Checking for required files ...
Copying 1 file ...
Copying 1 file ...
Copying 1 file ...
Copying and patching 1 file ...
Copying 1 file ...
Copying 1 file ...
Copying 1 file ...
Copying 1 file ...
Copying 1 file ...
Copying 1 file ...
Copying 1 file ...
Copying and patching 1 file ...
Copying and patching 1 file ...
Copying 1 file ...
Copying 1 file ...
Copying 1 file ...
Copying 1 file ...
Copying 1 file ...
Copying 1 file ...
Copying 1 file ...
Copying 1 file ...
Copying 1 file ...
Copying 1 file ...
Copying 1 file ...
Copying 1 file ...
Copying 1 file ...
Copying and patching 1 file ...
Copying 1 file ...
Processing BG1NPC\PHASE3\CHALLENGE\TIZ\X#CH12.TIZ...
Unpacking 1178 tiles in BG1NPC\PHASE3\CHALLENGE\TIZ\X#CH12.TIZ to override\X#CH12.tis
unpacked 256 tiles with method 0, 0 tiles with method 1, 922 tiles with method 2
Copying 1 file ...
Processing BG1NPC\PHASE3\CHALLENGE\TIZ\X#CH13.TIZ...
Unpacking 466 tiles in BG1NPC\PHASE3\CHALLENGE\TIZ\X#CH13.TIZ to override\X#CH13.tis
unpacked 129 tiles with method 0, 2 tiles with method 1, 335 tiles with method 2
Copying and patching 1 file ...
Appending to files ...
Copying and patching 1 file ...
Copying and patching 1 file ...
Copying and patching 2 files ...
Copying and patching 1 file ...
Copying and patching 1 file ...
Copying and patching 1 file ...
Copying and patching 1 file ...
Copying and patching 1 file ...
WARNING: REPLACE_CRE_ITEM: Unknown flag UNDROPPABLE&UNSTEALABLE. Defaulting to NONE for flags.
Copying and patching 1 file ...
Copying and patching 1 file ...
WARNING: REPLACE_CRE_ITEM: Unknown flag UNDROPPABLE&UNSTEALABLE. Defaulting to NONE for flags.
WARNING: REPLACE_CRE_ITEM: Unknown flag UNDROPPABLE&UNSTEALABLE. Defaulting to NONE for flags.
Copying and patching 1 file ...
WARNING: REPLACE_CRE_ITEM: Unknown flag UNDROPPABLE&UNSTEALABLE. Defaulting to NONE for flags.
WARNING: REPLACE_CRE_ITEM: Unknown flag UNDROPPABLE&UNSTEALABLE. Defaulting to NONE for flags.
...
[snipped]
...
INSTALLED WITH WARNINGS     The BG1 NPC Project: Female Romance Challenges, Ajantis vs Xan vs Coran

**Comment by AstroBryGuy** [comment]
Dang it. Had the flags backwards. Should be 'unstealable&undroppable'. Will fix.
