### ISSUE TITLE
[BGEE] ToTSC quests not closing

### ISSUE THREAD

**Issue by AstroBryGuy** [Gibberlings3/BG1NPC#25]
Reported by vanatos: http://gibberlings3.net/forums/index.php?showtopic=27360&p=252118

For the modification to the TotSC Kaishas (balduran werewolf) resolution in this mod for BG1EE
 
Specifically where you can get a nice resolution at the end rather then killing Kaishas.
 
The quests 'Last voyage of Balduran', 'Mysterious Island' and 'Reclusive Scholar' do not complete.

**Comment by Gitjas** [comment]
https://www.gibberlings3.net/forums/topic/27360-bg1npc-project-v22-bug-thread/page/8/#comment-252118

**Comment by Gitjas** [comment]
I don't think this is this mod - BG1NPC does not insert a modification to the werewolf island quest. The mods that do are (afaik) SCS (I *think* no longer) and TheCalling.
I'll close this.
