### ISSUE TITLE
tiny bugs

### ISSUE THREAD

**Issue by TotoR115** [Gibberlings3/BG1NPC#90]
- In nythrun_fixes.tpa: `ADD_MEMORIZED_SPELL ~spwi401~ #3 ~wizard~ (2) // Confusion` instead of `ADD_MEMORIZED_SPELL ~spwi401~ #2 ~wizard~ (2) // Confusion`
- on BGT, x#corafi.cre is equipped with _SW2h01 instead of SW2H01

**Comment by Gitjas** [comment]
spwi401 is a 4th level spell though, so #3 would be correct?

**Comment by Gitjas** [comment]
_SW2h01 reference removed for v28.

**Comment by TotoR115** [comment]
> spwi401 is a 4th level spell though, so #3 would be correct?

Yes you'r right... I don't remember why I written that down. Sorry for the trouble.

**Comment by Gitjas** [comment]
Thanks!

**Comment by TotoR115** [comment]
@Gitjas 
There are 3 instance of `ADD_MEMORIZED_SPELL ~spwi401~` in nythrun_fixes.tpa. 

two are correct: 
https://github.com/Gibberlings3/BG1NPC/blob/d4ab04576106f368847964e89f40ff494fd74f2a/bg1npc/core/tpa/nythrun_fixes.tpa#L791
https://github.com/Gibberlings3/BG1NPC/blob/d4ab04576106f368847964e89f40ff494fd74f2a/bg1npc/core/tpa/nythrun_fixes.tpa#L299

and one is not: https://github.com/Gibberlings3/BG1NPC/blob/d4ab04576106f368847964e89f40ff494fd74f2a/bg1npc/core/tpa/nythrun_fixes.tpa#L358

**Comment by Gitjas** [comment]
Aah. Thanks, will fix!
