### ISSUE TITLE
Cosmetic bug in Bg1NPC_kivan.tpa, line 46

### ISSUE THREAD

**Issue by Frenzgyn** [Gibberlings3/BG1NPC#98]
`APPEND ~item_use.2da~ ~P#BOW KIVAN 9382 2 9491~ //Cosmetic fix, turn "Usable by KIVAN" (capitals) into a more pleasant "Usable by Kivan"`

Adding Username "9491" (Kivan).

**Comment by Gitjas** [comment]
Thanks, will be changed in v28.
